### ISSUE TITLE
KeepassXCsvImporter does not create subfolders of subfolders

### ISSUE THREAD

**Issue by gringofe** [bitwarden/jslib#113]
When importing an exported CSV file from KeepassX, the import does not create subfolders of subfolders.

Example:
CSV contains `test/test2/test3`
This will create a folder called `test`, with a subfolder called `test2/test3` instead of a folder called `test2` which contains `test3`.

Workaround: 
Export to XML with Keepass2, and import XML with Bitwarden

**Comment by cscharf** [comment]
@gringofe , I noticed you had closed this bug, is this still an issue?

**Comment by gringofe** [comment]
Hello, 

I must have closed the issue by mistake, I have not seen any resolution for this poblem yet.

@cscharf

**Comment by gringofe** [comment]
Has this been fixed yet?
