### ISSUE TITLE
1password import misses a bunch of things

### ISSUE THREAD

**Issue by theontho** [bitwarden/jslib#18]
**1password import does not import 1p identities as bitwarden identities**

I imported a 1pif file which contained several identities. They were imported as secure notes, even though bitwarden has an identity type. You can tell they are identities by looking this field : "typeName":"identities.Identity"

**1password imports trashed items with no differentiation**

The 1pif file does tag trashed items with a "trashed":true, tag. Maybe bitwarden can automatically put them in one category for easy categorization, such as a '1password import trashed items'. Another alternative would be to implement a trashbin feature and put those imported items into the new trashbin.

**1 password import does not import the password part of password items**

In a 1pif import "typeName":"passwords.Password" items do not have their passwords fields imported, but instead show up as weird stub items

"typeName":"webforms.WebForm do seem to get imported properly

This came from a 1password 6.8.9 export

**1password import does not import password history**
There are password history fields in 1pif items ("passwordHistory":), so it's something bitwarden could import too.

**1password import doesn't import attachments**
For example, I have pictures attached to my credit cards and id card items. 1 password export does export the attachments, but bitwarden import does not.

**Comment by kspearrin** [comment]
identities and history are now imported per the above referenced PRs

**Comment by saphirblanc** [comment]
What would be really, really useful is to import the tags as collections (if imported in an organization) or Folders if imported in a personal vault. Obviously, if the tags is written like "IT/Client/XXX", this should be the same in Bitwarden. Please :-), currently doing it by hand.

**Comment by djsmith85** [comment]
Closing this now.

- Improvements to the existing 1pif importer have been made as mentioned by Kyle and can still be used.

- 1password has since replaced the `.1pif` with the new `.1pux` format. To also support this format, we have created a new importer. Details which cases it handles can be found at #594
