### ISSUE TITLE
Additional Options in Password Generation

### ISSUE THREAD

**Issue by ashvinnihalani** [bitwarden/jslib#415]
It would be great if the passphrase generation had some more options/refinements, namely:

1) Randomly select a character from a subset as the separator between words
2) Min/Max Character Sizes for the word character sizes
3) Add a number after every single word, instead of just one
4) Randomly capitalize each word instead of just capitalizing all of them or none of them

I have seen this implemented in other password managers and it greatly increases the entropy of the password especially if the attacker already knows that the password was created by Bitwarden. 

I would be happy to do the coding work if someone can direct me to the correct places. I know that I would have to change the passwordGeneration.service.ts and the passwordGeneratorPolicyOptions files. Are there other features I would have to change in order to get into the UI.

**Comment by cscharf** [comment]
Hi @ashvinnihalani , thank you for your post, however we use GitHub for tracking issues. I would highly suggest for something like this, going to our [Community Forum's GitHub Contributions](https://community.bitwarden.com/c/github-contributions/7) topic and posting your idea there, gathering any input and support from the community, Bitwarden devs and product team, etc. to determine if this is something worthwhile undertaking.

Thanks!
~ Chad
