### ISSUE TITLE
All type 4 "random" GUIDs aren't following RFC 4122

### ISSUE THREAD

**Issue by atoponce** [bitwarden/jslib#44]
Executing the following, i noticed that the GUIDs are not quite following [RFC 4122](https://tools.ietf.org/html/rfc4122#section-4.4):

    $ bw list items | jq '.[].id' | awk -F '[-"]' '{print $6}' | sort
    a7ef016698b9
    a7ef017a7a96
    a7f2010cf0c5
    a7f2011d21ff
    a7f20174676e
    a7f3011d3ffb
    a7f3015ae816
    a7f301688f0e
    a7f301780bc3
    a7f901482b5c
    a7f90177367c
    a7fc01038595
    a7fc010d0f1c
    a7fc0156518a
    a8000167ec93
    a8000175d320
    a816016f932c
    a817015eeab2
    a81701602d93
    a81f016b140b
    a8200113fb52
    a82001701e26
    a823018386cb
    a824017fb706
    a82500114bd8
    a82500124e9a
    a8250188b1b7
    a825018af619
    a82701359912
    a82a0138a296
    a82a015c80fe
    a82a0177e0c8
    a82e011d909d
    a83e01083b14
    a846013c1861
    a8480114d6bd
    a8480172f9f6
    a8500126decd
    a8500128283f
    a85601356e1b
    a857000d86fd
    a857000e2ccb
    a857000f8117
    a857000fbe1a
    a85d00d59800
    a8640129e5d0
    a86401300f66
    a8650168b18d
    a86e0004fa26
    a8710157bd3a
    a8890113a0d6
    a89c0147ac1a
    a8b200e53f33
    a8b400ecaa37
    a8c301721cdd
    a8c3017cd8f2
    a8ca00262368
    a8ca00e0df9a
    a8ca00ef81b9
    a8d800e77308
    a8ec00eea2b4
    a8ec00efe635
    a8ec00f162a6
    a8ec00f3924b
    a8ec00f4fd83
    a8ed013de6ff
    a8fa01253f71
    a90b0172cf5f
    a90c002c29a4
    a90c0035925e
    a915007269a0
    a91b01206c24
    aa190125430b
    aa680157c4b3
    aa68015803a5
    aa680158a11c
    aa6801628bf5
    aa6801632ba3
    aa6801635ff5
    aa680163988b
    aa680163f17d
    aa6801649379
    aa680164d4b2
    aa68016549f9
    aa680165c739
    aa68016a33bb
    aa69001f2ee9
    aa69001f6f48
    aa69001fb211
    aa69001fede8
    aa690020f6c8
    aa69002135eb
    aa69002165aa
    aa690021c097
    aa690022a73d
    aa69002347fa
    aa690023ae2e
    aa69002427e2
    aa6900246498
    aa690024c2e0
    aa6900250555
    aa6900253191
    aa69002568d2
    aa690026b333
    aa6900289558
    aa6900292576
    aa6900296b6e
    aa690029ea1b
    aa69002a4a63

As you can see, the 6th byte is always one of `0xa[789a]`. If the 6th byte is `0xaa`, then the 5th byte is either `0x68` or `0x69`. Further, if the 6th and 5th bytes are `0xaa69`, then the 4th byte is always `0x00`. You can see other patterns in the output. It's also consistent when getting folder IDs.

Is this expected, or a bug?

**Comment by kspearrin** [comment]
These guids are generated on the server at the time of item creation. We use a custom GUID algorithm to created sequential GUIDs (otherwise known as Comb guids). This is for performance reasons in the database.

See https://github.com/bitwarden/server/blob/master/src/Core/Utilities/CoreHelpers.cs#L35

**Comment by atoponce** [comment]
I'll close this then. I was pouring over the code, and couldn't see where it was getting modified. Thanks for the reply.
