### ISSUE TITLE
"duo_web_sdk" dependency is used by "angular" package but the dependency is declared elsewhere

### ISSUE THREAD

**Issue by libertylocked** [bitwarden/jslib#440]
Hi Bitwarden team,

I noticed that the [two-factor.component.ts file](https://github.com/bitwarden/jslib/blob/ecdd08624f61ccff8128b7cb3241f39e664e1c7f/angular/src/components/two-factor.component.ts#L25) imports 'duo_web_sdk', however this dependency is nowhere declared in angular or jslib package.

It is actually declared in [the desktop package's package.json](https://github.com/bitwarden/desktop/blob/20561fff8703eefa356719662eeb88aea80e01ea/package.json#L296).

I'm not sure if it's intentional, but it seems like the dependency should be declared at where it is used, i.e. in [jslib/angular/package.json](https://github.com/bitwarden/jslib/blob/ecdd08624f61ccff8128b7cb3241f39e664e1c7f/angular/package.json#L26).

I'm the maintainer of the Arch User Repository of bitwarden (https://aur.archlinux.org/packages/bitwarden/) and our current build script complains when `two-factor.component.ts` tries to import a dep that's not declared in the package. It seems to build fine if I patch `jslib/angular/package.json` tho.

Thanks

**Comment by djsmith85** [comment]
@libertylocked Thank you for your report and research. I've experienced a similar behaviour while setting up my dev environment. I'll have look into it, this evening.
