### ISSUE TITLE
Utils.getDomain is broken on ipv6 host uris

### ISSUE THREAD

**Issue by fahrradflucht** [bitwarden/jslib#545]
Bitwardens domain based detection scheme unexpectedly doesn't detect matching logins when visiting URIs like `http://[2001:db8:0:0:0:0:2:1]` or `https://[2001:db8::2:1]`. I suspect this is because `Utils.getDomain` returns `null` instead of `[2001:db8::2:1]` when calling it on such URIs.

**Comment by djsmith85** [comment]
@fahrradflucht Thank you for your report. This is most probably the root cause for https://github.com/bitwarden/browser/issues/2107

**Comment by eliykat** [comment]
I'm closing this as a duplicate of https://github.com/bitwarden/browser/issues/2107. Please refer to that issue for any further updates.

**Comment by eliykat** [comment]
I'm closing this as a duplicate of https://github.com/bitwarden/browser/issues/2107. Please refer to that issue for any further updates.
