### ISSUE TITLE
In what file/function is search performed?

### ISSUE THREAD

**Issue by imthenachoman** [bitwarden/jslib#55]
I am a BW user. One of my biggest gripes is the lousy search algorithm that uses OR instead of AND. I've seen very old feature requests in the forums but no change/update. I'm a programmer so I thought I'd see if I could clone the repo and make some changes myself. I looked through the code; it's pretty complex.

Looking through the [web code](https://github.com/bitwarden/web), I thought the search algorithm would be defined in `jslib/abstractions/search.service` but I can't figure out where to go from [there](https://github.com/bitwarden/jslib/blob/9ba3c176262b7d06209998305ab73d91c3e72458/src/abstractions/search.service.ts).

If I spend a few days/weeks I could probably find the relevant area I need to tweak.

In the interest of time, I'm hoping someone could point me to the file/function responsible for actually doing the search. I just want to change the logic to use AND instead of OR. 

Any pointers are appreciated.

**Comment by kspearrin** [comment]
We use https://lunrjs.com/ in the search service here https://github.com/bitwarden/jslib/blob/master/src/services/search.service.ts

From my understanding, lunrjs uses ORs and you cannot change that.

**Comment by imthenachoman** [comment]
Humm. It looks like this can be changed. Per their documentation at https://lunrjs.com/guides/searching.html#term-presence:

> This behaviour is controllable at the term level, i.e. the presence of each term in matching documents can be specified.

Not entirely sure what that means or how it fits into BitWarden. I will try to dig a little more.

The documentation also says we should be able to use `+`/`-` to force inclusion of terms:

> To indicate that a term must be present in matching documents the term should be prefixed with a plus (+) and to indicate that a term must be absent the term should be prefixed with a minus (-). Without either prefix the term’s presence in matching documents is optional.

However, this does not seem to work from BitWarden.

**Comment by imthenachoman** [comment]
I think some changes have to be made to https://github.com/bitwarden/jslib/blob/master/src/services/search.service.ts#L119. I am getting close; I think. Heh.

**Comment by MGibson1** [comment]
It looks like this works to me. You need to prepend each search term with a `+` to indicate AND

### OR operation
![image](https://user-images.githubusercontent.com/18214891/106486310-1f109b80-6477-11eb-86b8-21bb8a067df6.png)

### AND operation
![image](https://user-images.githubusercontent.com/18214891/106486225-0acc9e80-6477-11eb-9144-88c64ce917a8.png)

**Comment by imthenachoman** [comment]
Having to enter advanced strings to search is not user friendly. When you search Google for "phrase1 phrase2" do you expect it to use `OR` or `AND`? Sure you can use advanced search strings but the default behavior is AND. It's rather foolish, IMHO, for a PW vault to default to `OR` when searching for entries. It's not the norm.

In fact, there are many in the forums saying the same thing. The current use of `OR` is a horrible UX. 

When I looked through the code last I think I found a way to change the default behavior. I just don't have an environment I can play around with the code to test in. 

For now I am hoping the developers listen to the users ([link](https://community.bitwarden.com/t/search-combine-search-terms-rathen-than-add-them-up/4931)) and either change the default behavior or offer a setting for changing the default behavior.

**Comment by MGibson1** [comment]
Thanks for bringing my attention to that community thread, I'd missed it.

I also am guilty of misunderstanding your ask and throwing too much at you. I thought you were interested in filtering different fields rather than improving your more general search results.

At any rate, I've thrown a post onto that community thread I hope may be helpful to those troubled by the current search.

**Comment by imthenachoman** [comment]
Yes, I still need help. Bitwarden's search feature is a horrible user experience. It's wholly uncommon for search features to use a binary `OR`. Any chance we can get the search feature to use a binary `AND` like every other tool with a search box?

**Comment by dwbit** [comment]
Hey @imthenachoman, the best place to continue the search conversation is in the community forums, in posts like this [one](https://community.bitwarden.com/t/search-combine-search-terms-rathen-than-add-them-up/4931/19).

Since this is an open discussion and not a bug report, I'll close the issue now.

**Comment by imthenachoman** [comment]
@dwbit 

My original question is still out-standing. I am looking for help/guidance on where exactly the search happens in the BitWarden code so I can change it and submit a pull request.

**Comment by dwbit** [comment]
Hi @imthenachoman, the best place for questions/discussions are the Bitwarden Community Forums, specifically the [Github Contributer's](https://community.bitwarden.com/c/github-contributions) category in this case, which the team can then review.
