### ISSUE TITLE
Toggle Visibility of the master password move cursor to start of input

### ISSUE THREAD

**Issue by chao813** [bitwarden/jslib#557]
On Chrome, when you toggle visibility of the master password, the cursor moves to the start of the input field. Noticed it does this on Chrome web vault and Chrome browser extension. I tried on Safari and can't reproduce this issue. 

There was an issue [(browser#2178)](https://github.com/bitwarden/browser/issues/2178) opened in the browser repo but since the code is in jslib, thought I'd open an issue here. I have a work around but was wondering if this was already tackled before I open a pull request.

**Comment by eliykat** [comment]
Hi @chao813, thanks for creating this issue and the PR. It can be a bit difficult tracking issues across all our different client repos, however let's just use https://github.com/bitwarden/browser/issues/2178 to track this issue so that we're not creating duplicates.
