### ISSUE TITLE
OnePasswordCsvImporter does not import URIs

### ISSUE THREAD

**Issue by newtonle** [bitwarden/jslib#596]
I've tried using the web front-end to import a CSV exported from Mac 1Password 7. I've confirmed the exported CSV has URL fields populated but no URIs are populated in BitWarden.

**Comment by djsmith85** [comment]
Hi @newtonle thank you for reporting this. 

Have you checked our guide [here](https://bitwarden.com/help/import-from-1password/)?

Does the csv-file include the headers?

If you are still experiencing issues, could you please attach a redacted example file?

**Comment by djsmith85** [comment]
Hi @newtonle, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
