### ISSUE TITLE
1password import failed

### ISSUE THREAD

**Issue by iovw** [bitwarden/jslib#84]
some log:

```
Error parsing row 198: Too few fields: expected 70 fields but parsed 66
```

**Comment by kspearrin** [comment]
I need more information. What importer are you using? 1pif, csv? Can you provide an example that can reproduce this error?

**Comment by iovw** [comment]
Yeah, I'm using csv importer. And now may I found the reason.
Just because some extra information is saved in the csv file.After delete these, it works.

**Comment by iovw** [comment]
I had done the irreversible operation in 1password, so can't reproduce it.
I'm sorry.

**Comment by iovw** [comment]
I noticed it have these fields in the normal csv file.

ainfo | autosubmit | notesPlain | password | scope | section:linked items | tags | title | urls | username | uuid
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

But it have the following fields in the real csv file.

/paypalAccountData/email | /paypalAccountData/password | ainfo | autosubmit | confirmation_code | dwfrm_profile_customer_email | email | Email | Email: | emailAddress | form[new_password] | itemField1 | itemField2 | login_email | login_password | mail | notesPlain | pass | password | Password | ppwd | previousPassword1 | previousPassword2 | register[password] | register[username] | register_password | scope | section:linked items | section:OpenYOLO_Details | tags | title | TYJ4wK | urls | user[email] | user[name] | user[password] | user[password_confirmation] | user_pass | userLoginId | UserMember[realname] | username | uuid
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


And sometime it have more.
